import { StyleSheet } from "react-native";

export const palette = {
  background: "#0a0f10",
  surface: "#12191b",
  surfaceMuted: "#171f22",
  border: "rgba(255, 255, 255, 0.08)",
  borderSoft: "rgba(255, 255, 255, 0.12)",
  ink: "#f5f8f7",
  inkMuted: "#a2acab",
  inkSubtle: "#7d8684",
  deep: "#0a0f10",
  deepSoft: "#87d8c3",
  accentSurface: "rgba(255, 255, 255, 0.05)",
  accentMint: "#87d8c3",
  userBubble: "#174447",
  userBubbleText: "#ffffff",
  error: "#b24534",
  chatCanvas: "#0a0f10",
  chatSurface: "#12191b",
  chatSurfaceSoft: "#171f22",
  chatBorder: "rgba(255, 255, 255, 0.08)",
  chatText: "#f5f8f7",
  chatMuted: "#a2acab",
  chatSubtle: "#7d8684",
  chatAccent: "#87d8c3",
  chatError: "#ffb09a",
} as const;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: palette.background,
  },
  safeArea: {
    flex: 1,
  },
  connectingRoot: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  connectingText: {
    color: palette.inkMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  shell: {
    flex: 1,
    backgroundColor: palette.background,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: "rgba(10, 15, 16, 0.96)",
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  topBarThread: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 17,
    backgroundColor: "rgba(10, 15, 16, 0.96)",
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  topBarLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flex: 1,
  },
  topBarCopy: {
    flex: 1,
    gap: 2,
  },
  eyebrow: {
    color: palette.inkMuted,
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  topBarTitle: {
    color: palette.ink,
    fontSize: 18,
    lineHeight: 28,
    fontWeight: "700",
    letterSpacing: -0.45,
  },
  headerButton: {
    width: 36,
    height: 36,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.accentSurface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  projectListContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 140,
    gap: 8,
  },
  projectCard: {
    borderRadius: 32,
    paddingHorizontal: 22,
    paddingVertical: 20,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  projectLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  projectCopy: {
    flex: 1,
    gap: 4,
  },
  projectTitle: {
    color: palette.ink,
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "700",
  },
  projectPath: {
    color: palette.inkMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  fab: {
    position: "absolute",
    right: 24,
    bottom: 32,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: palette.deepSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.border,
  },
  threadListContent: {
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 64,
    gap: 10,
  },
  threadCard: {
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  threadCardCopy: {
    flex: 1,
    gap: 6,
  },
  threadCardTitle: {
    color: palette.ink,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "700",
  },
  threadCardMeta: {
    color: palette.inkSubtle,
    fontSize: 12,
    lineHeight: 18,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  emptyStateCard: {
    borderRadius: 26,
    paddingHorizontal: 22,
    paddingVertical: 24,
    backgroundColor: palette.surfaceMuted,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 8,
    alignItems: "center",
  },
  emptyStateTitle: {
    color: palette.ink,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  emptyStateText: {
    color: palette.inkMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  inlineError: {
    color: palette.error,
    fontSize: 14,
    lineHeight: 21,
  },
  stateRoot: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: "center",
    gap: 20,
    backgroundColor: palette.background,
  },
  stateActions: {
    gap: 12,
  },
  blockedTitle: {
    color: palette.ink,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "700",
  },
  blockedText: {
    color: palette.inkMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  chatRoot: {
    flex: 1,
    backgroundColor: palette.chatCanvas,
  },
  chatSafeArea: {
    flex: 1,
    backgroundColor: palette.chatCanvas,
  },
  chatTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: palette.chatBorder,
    backgroundColor: "rgba(10, 15, 16, 0.96)",
  },
  chatHeaderButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
  },
  chatTitle: {
    color: palette.chatText,
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "700",
  },
  chatSubtitle: {
    color: palette.chatMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  chatContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 24,
    gap: 18,
  },
  chatBody: {
    flex: 1,
  },
  chatMessagesContainer: {
    flex: 1,
  },
  chatListHeader: {
    gap: 18,
  },
  chatContextCard: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    backgroundColor: palette.chatSurface,
    borderWidth: 1,
    borderColor: palette.chatBorder,
    gap: 8,
  },
  chatContextLabel: {
    color: palette.chatSubtle,
    fontSize: 11,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  chatContextValue: {
    color: palette.chatText,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  chatContextSubtext: {
    color: palette.chatMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  chatContextMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chatContextMetaText: {
    color: palette.chatMuted,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  runningState: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  runningDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: palette.chatAccent,
  },
  runningText: {
    color: palette.chatMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  hasMoreBanner: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderWidth: 1,
    borderColor: palette.chatBorder,
  },
  hasMoreText: {
    color: palette.chatMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  chatEmptyState: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    paddingVertical: 28,
    alignItems: "center",
    gap: 10,
  },
  chatEmptyTitle: {
    color: palette.chatText,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  chatEmptyText: {
    color: palette.chatMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  chatInlineError: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    color: palette.chatError,
    fontSize: 13,
    lineHeight: 20,
  },
  messageRowWrap: {
    width: "100%",
  },
  codexEntry: {
    width: "100%",
    alignItems: "center",
  },
  codexBody: {
    width: "100%",
    maxWidth: 900,
    gap: 12,
  },
  systemAccentLabel: {
    color: palette.chatSubtle,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  caption: {
    color: palette.chatSubtle,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  userEntry: {
    width: "100%",
    alignItems: "center",
  },
  userBubbleWrap: {
    width: "100%",
    maxWidth: 900,
    alignItems: "flex-end",
    gap: 6,
  },
  userBubble: {
    maxWidth: "78%",
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: palette.userBubble,
    gap: 12,
  },
  userCaption: {
    color: "rgba(255, 255, 255, 0.72)",
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  timestamp: {
    color: palette.chatSubtle,
    fontSize: 11,
    lineHeight: 16,
  },
  summaryRow: {
    width: "100%",
    alignItems: "center",
  },
  summaryCard: {
    width: "100%",
    maxWidth: 900,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.chatBorder,
    backgroundColor: palette.chatSurface,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 14,
  },
  summaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  summaryTitle: {
    color: palette.chatText,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    flex: 1,
  },
  summaryMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  summaryMetaText: {
    color: palette.chatMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  summaryNote: {
    color: palette.chatText,
    fontSize: 14,
    lineHeight: 22,
  },
  summaryFiles: {
    gap: 8,
  },
  summaryFileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  summaryFileCopy: {
    flex: 1,
  },
  summaryFileLabel: {
    color: palette.chatText,
    fontSize: 13,
    lineHeight: 20,
  },
  summaryDelta: {
    color: palette.chatMuted,
    fontSize: 12,
    lineHeight: 18,
    fontVariant: ["tabular-nums"],
  },
  summaryState: {
    color: palette.chatMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  summaryActionButton: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryActionSecondary: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  summaryActionGhost: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: palette.chatBorder,
  },
  summaryActionDanger: {
    backgroundColor: "rgba(255, 99, 99, 0.16)",
  },
  summaryActionDisabled: {
    opacity: 0.5,
  },
  summaryActionLabel: {
    color: palette.chatText,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  userInputCard: {
    width: "100%",
    maxWidth: 900,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.chatBorder,
    backgroundColor: palette.chatSurface,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 16,
  },
  userInputHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  userInputState: {
    color: palette.chatAccent,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  userInputQuestions: {
    gap: 14,
  },
  userInputQuestion: {
    gap: 10,
  },
  userInputQuestionHeader: {
    color: palette.chatSubtle,
    fontSize: 11,
    lineHeight: 15,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  userInputQuestionText: {
    color: palette.chatText,
    fontSize: 14,
    lineHeight: 22,
  },
  userInputOptions: {
    gap: 10,
  },
  userInputOption: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.chatBorder,
    backgroundColor: palette.chatSurfaceSoft,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 4,
  },
  userInputOptionSelected: {
    borderColor: "rgba(135, 216, 195, 0.56)",
    backgroundColor: "rgba(135, 216, 195, 0.12)",
  },
  userInputOptionLabel: {
    color: palette.chatText,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  userInputOptionDescription: {
    color: palette.chatMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  userInputOtherWrap: {
    gap: 10,
  },
  userInputOtherInput: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.chatBorder,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    color: palette.chatText,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
  },
  userInputAnswerSummary: {
    color: palette.chatMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  userInputActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  attachmentChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  attachmentChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    maxWidth: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderColor: palette.chatBorder,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  attachmentChipText: {
    color: palette.chatMuted,
    fontSize: 12,
    lineHeight: 18,
    maxWidth: 240,
  },
  attachmentChipRemove: {
    width: 18,
    height: 18,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  attachmentImage: {
    width: "100%",
    maxWidth: 520,
    aspectRatio: 1.6,
    borderRadius: 18,
    backgroundColor: "#10171a",
  },
  attachmentLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: palette.chatBorder,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  attachmentLinkText: {
    color: palette.chatText,
    fontSize: 13,
    lineHeight: 18,
  },
  attachmentFallback: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  attachmentFallbackText: {
    color: palette.chatMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  chatComposerRail: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    backgroundColor: "rgba(10, 15, 16, 0.96)",
    borderTopWidth: 1,
    borderTopColor: palette.chatBorder,
    gap: 12,
  },
  chatControlRow: {
    gap: 8,
    paddingRight: 12,
  },
  controlChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.chatBorder,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  controlChipActive: {
    backgroundColor: "rgba(135, 216, 195, 0.14)",
    borderColor: "rgba(135, 216, 195, 0.36)",
  },
  controlChipDisabled: {
    opacity: 0.55,
  },
  controlChipText: {
    color: palette.chatMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  controlChipTextActive: {
    color: palette.chatText,
  },
  chatComposer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 12,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.chatBorder,
    backgroundColor: palette.chatSurface,
    paddingLeft: 16,
    paddingRight: 10,
    paddingTop: 12,
    paddingBottom: 10,
  },
  chatComposerInput: {
    flex: 1,
    minHeight: 42,
    maxHeight: 160,
    color: palette.chatText,
    fontSize: 15,
    lineHeight: 22,
    paddingVertical: 0,
  },
  chatSendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.deepSoft,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.16)",
  },
  chatSendButtonDisabled: {
    opacity: 0.45,
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  sheetCard: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: palette.chatSurface,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 28,
    gap: 16,
  },
  sheetTitle: {
    color: palette.chatText,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
  },
  sheetOptions: {
    gap: 10,
  },
  sheetOption: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.chatBorder,
    backgroundColor: palette.chatSurfaceSoft,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  sheetOptionSelected: {
    borderColor: "rgba(135, 216, 195, 0.42)",
    backgroundColor: "rgba(135, 216, 195, 0.12)",
  },
  sheetOptionCopy: {
    flex: 1,
    gap: 4,
  },
  sheetOptionLabel: {
    color: palette.chatText,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  sheetOptionDescription: {
    color: palette.chatMuted,
    fontSize: 12,
    lineHeight: 18,
  },
});
